version: '3'

services:
  web:
    build: .
    command: sh -c "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: mysql:latest
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    env_file:
      - .env
    restart: always

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A library.celery worker --loglevel=info
    depends_on:
      - web
      - redis
    env_file:
      - .env
